default_login:
  user1@emailadrress.fr: passwd1

logins:
  dummy-email@foobar.com:
    cdse-psswd: passwd1
    s3-access-key: a-s3-key
    s3-secret: a-s3-secret
  user2@emailadrress.fr:
    cdse-psswd: passwd2
    s3-access-key: s3-key2
    s3-secret: s3-secret2
URL_identity: https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token
URL_download: https://zipper.dataspace.copernicus.eu/odata/v1/Products(%s)/$value
spools:
  default: "./my_spool"
pre_spool: "./sentinel1_cdse_pre_spool"
archives:
  default: "./my_archive"
test_default_output_directory: "./my_tests"
s3_endpoint: "https://eodata.dataspace.copernicus.eu"
s3_bucket: "eodata"
s3_region: "default"
list_sar_unit_private_data:
  - S1E
  - S1F
