# This file contains values from Cookiecutter

default_context:
  project_name: "cdsodatacli"
  project_description: "odata client for Copernicus Data Space catalog"
  organization: "umr-lops"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "cdsodatacli"
  email: "jrmiadan@ifremer.fr"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
