name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          environment-file: ci/requirements/docs.yaml
          python-version: "3.11"
          activate-environment: docs
          auto-activate-base: false

      - name: Install package
        run: pip install -e .[docs]

      - name: Build Sphinx docs
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html

  deploy:
    needs: build-docs

    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      github.actor != 'dependabot[bot]'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
